name: ERPort Sequence

on:
  workflow_call:
    inputs:
      erport:
        required: true
        type: string

jobs:
  approval-1:
    runs-on: ubuntu-latest
    environment:
      name: erport-approval-${{ inputs.erport }}
    steps:
      - name: Awaiting Manual Approval for ${{ inputs.erport }}
        run: echo "Approved to proceed with ${{ inputs.erport }}"

  powershell-step:
    needs: approval-1
    runs-on: windows-latest
    steps:
      - name: Run PowerShell Script for ${{ inputs.erport }}
        shell: pwsh
        run: |
          Write-Host "Running PowerShell script for ${{ inputs.erport }}"

  approval-2:
    needs: powershell-step
    runs-on: ubuntu-latest
    environment:
      name: erport-final-approval-${{ inputs.erport }}
    steps:
      - name: Final Manual Approval for ${{ inputs.erport }}
        run: echo "Final approval granted for ${{ inputs.erport }}"
