name: ERPort Sequence

on:
  workflow_call:
    inputs:
      erport:
        required: true
        type: string

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

  approval-1:
    needs: checkout
    runs-on: ubuntu-latest
    environment:
        name: approval-stage-2
    steps:
      - name: Awaiting Final Manual Approval for ${{ inputs.erport }}
        run: echo "Final approval granted for ${{ inputs.erport }}"

  powershell-step:
    needs: approval-1
    runs-on: windows-latest
    steps:
      - name: Run PowerShell Script for ${{ inputs.erport }}
        run: |
          Write-Host "Running script for ${{ inputs.erport }}"

  approval-2:
    needs: powershell-step
    runs-on: ubuntu-latest
    steps:
      - name: Awaiting Final Manual Approval for ${{ inputs.erport }}
        run: echo "Final approval granted for ${{ inputs.erport }}"
